name: Build LaTeX document
permissions:
  contents: write
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Update 'latest' tag
        uses: EndBug/latest-tag@latest
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            main.tex
          post_compile: "latexmk -c"
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            main.pdf
